### ISSUE TITLE
Boss still yeets itself off the screen during rain from above spellcard

### ISSUE THREAD

**Issue by pterozactyl** [Astral-Beast/BulletHellJamMay24#147]
Really not sure what's happening because I can't see the health bar

**Comment by Astral-Beast** [comment]
Is it an issue with the timeout curve update?

**Comment by pterozactyl** [comment]
Honestly no idea. It doesn't happen every time

**Comment by pterozactyl** [comment]
I actually just witnessed it happen on the spellcard after "rain from above"

**Comment by pterozactyl** [comment]
Bruh this is the most annoying bug on the planet I swear
