### ISSUE TITLE
Make a boss-type enemy with a health bar

### ISSUE THREAD

**Issue by pterozactyl** [Astral-Beast/BulletHellJamMay24#33]
other considerations:
1. Complex patterns. This could consist of multiple patterns on top of one another but using different bullets
2. Timeouts in case player DPS is too low. Think Touhou spellcards
3. Should this just be a Foe, or should it be a copy/paste of the basics of a Foe + extra nodes?

**Comment by pterozactyl** [comment]
This can be deferred until we have a few more shot movement types and patterns, but shouldn't be deferred for too much longer

**Comment by Astral-Beast** [comment]
@pterozactyl I think we can extend foe like we extend normal nodes. I'll look into this
