### ISSUE TITLE
Add constant-pause-aimed dynamic bullet movement type

### ISSUE THREAD

**Issue by pterozactyl** [Astral-Beast/BulletHellJamMay24#37]
I am thinking something along the lines of a circle of bullets spawns in and extends for X seconds, then all bullets pause for Y seconds, then they all move directly towards player's current position.

**Comment by Astral-Beast** [comment]
CONST_PAUSE_AIM sound good for the Shot_Movement Enum?
@pterozactyl

**Comment by pterozactyl** [comment]
Fine for now, we can always change it later
